"""add scheduled monitoring

Revision ID: 914d6633f484
Revises: 9fae8082f517
Create Date: 2026-10-02 10:38:45.204000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914d6633f484'
down_revision: Union[str, Sequence[str], None] = '9fae8082f517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitorings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitorings_keyword'), 'monitorings', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitorings_keyword'), table_name='monitorings')
    op.drop_table('monitorings')
    # ### end Alembic commands ###
